### EXT:fluid_styled_content overrides
styles:
  templates:
    layoutRootPath: 'EXT:rlt3sitepackage/Resources/Private/Extensions/FluidStyledContent/Layouts'
    partialRootPath: 'EXT:rlt3sitepackage/Resources/Private/Extensions/FluidStyledContent/Partials'
    templateRootPath: 'EXT:rlt3sitepackage/Resources/Private/Extensions/FluidStyledContent/PageView'
  content:
    defaultHeaderType: 2
    textmedia:
      maxW: 1200
      maxWInText: 600
      linkWrap:
        width: 1200m
        height: 900m
        lightboxEnabled: true
        lightboxCssClass: 'lightbox'
        lightboxRelAttribute: 'lightbox'
